server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $gateway_upstream gateway:8500;
        proxy_pass http://$gateway_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
